# **MÓDULO 15 - Exercício**
# Análise  - A segunda etapa da Pré Modelagem

# 1) O primeiro exercício é o de salvar a base que criaram na atividade do módulo anterior em csv e abrir ela neste arquivo.
Igual fizemos no início do módulo atual no início da primeira aula.

In [65]:
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
from sklearn.ensemble import RandomForestClassifier

In [2]:
#Seu código de importação aqui
df = pd.read_csv("CHURN_TRATADO.csv", delimiter=",")
df.head(10)

,Unnamed: 0,customerID,Genero,Idoso,Casado,Dependentes,Tempo_como_Cliente,Servico_Telefonico,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,Forma_Pagamento,Pagamento_Mensal,Total_Pago,Churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.850000,29.85,No
1,1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.950000,1889.50,No
2,2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.850000,108.15,Yes
3,3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),40.905556,1840.75,No
4,16,8191-XWSZG,Female,0,No,No,52,Yes,No,No internet service,No internet service,No internet service,One year,Mailed check,19.672115,1022.95,No
5,17,9959-WOFKT,Male,0,No,Yes,71,Yes,Fiber optic,Yes,No,Yes,Two year,Bank transfer (automatic),103.975352,7382.25,No
6,18,4190-MFLUW,Female,0,Yes,Yes,10,Yes,DSL,No,Yes,No,Month-to-month,Credit card (automatic),52.835000,528.35,Yes
7,19,4183-MYFRB,Female,0,No,No,21,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,88.709524,1862.90,No
8,20,8779-QRDMV,Male,1,No,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,39.650000,39.65,Yes
9,21,1680-VDCWW,Male,0,Yes,No,12,Yes,No,No internet service,No internet service,No internet service,One year,Bank transfer (automatic),16.854167,202.25,No

In [3]:
df = df.replace({'Yes':1,'No':0})
df = df.replace({'No internet service':0})


colunas = ['Servico_Seguranca','Suporte_Tecnico','StreamingTV','Casado','Dependentes','Churn']

df[colunas] = df[colunas].astype(int)

In [4]:
print(df.dtypes)

Unnamed: 0              int64
customerID                str
Genero                    str
Idoso                   int64
Casado                  int64
Dependentes             int64
Tempo_como_Cliente      int64
Servico_Telefonico     object
Servico_Internet       object
Servico_Seguranca       int64
Suporte_Tecnico         int64
StreamingTV             int64
Tipo_Contrato             str
Forma_Pagamento           str
Pagamento_Mensal      float64
Total_Pago            float64
Churn                   int64
dtype: object

# 2) Comece pela análise univariada:

A) Utilize a função describe no seu dataframe, veja os insights que consegue retirar.

B) Já é possível identificar variáveis com possíveis outliers? Se sim, quais?

C) Plot gráficos que considerar importante para completar sua análise univariada. (Lembrando que sua variável preditora é o churn). Não se esqueça de trazer insights de cada gráfico plotado. Utilize pelo menos 4 variáveis distintas.

D) Verifique se os dados das variáveis Booleanas são balanceados ou não.

In [5]:
#Seu código aqui
df.describe()
# A) Podemos observar que grande parte dos dados na coluna 'Tempo_como_Cliente' está concentrada no Q3, assim como há uma grande diferença entre o mínimo e o máximo. Com essas observações, podemos esperar a presença de outliers acima da média. O mesmo não se aplica ao 'Total_Pago', onde grande partes do dados se concentram no Q2, porém este valor não condiz com a média, o que nos leva a concluir a presença de outliers. A coluna 'Pagamento_Mensal' possui o valor de desvio pedrão baixo em relação a média, isso nos mostra que os dados estão em sua maioria concentrados ao redor da média, e as medidas de Q1 e Q3 demonstram este comportamento, a semelhança entre média mediana também contribui com o pensamento da presença de poucos ou nenhum outlier.

,Unnamed: 0,Idoso,Casado,Dependentes,Tempo_como_Cliente,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Pagamento_Mensal,Total_Pago,Churn
count,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000
mean,1255.480707,0.161576,0.492765,0.314711,32.352090,0.284164,0.285772,0.385852,65.511708,2290.087178,0.260048
std,718.401587,0.368135,0.500048,0.464494,24.636885,0.451106,0.451872,0.486894,29.920953,2264.585643,0.438749
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.725000,18.800000,0.000000
25%,633.750000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,0.000000,39.637500,402.337500,0.000000
50%,1255.500000,0.000000,0.000000,0.000000,29.000000,0.000000,0.000000,0.000000,71.100000,1402.900000,0.000000
75%,1877.250000,0.000000,1.000000,1.000000,56.000000,1.000000,1.000000,1.000000,90.250000,3867.162500,1.000000
max,2499.000000,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,1.000000,121.400000,8564.750000,1.000000

In [6]:
mediana_pagamento = df['Pagamento_Mensal'].median()
mediana_tempo = df['Tempo_como_Cliente'].median()
mediana_total = df['Total_Pago'].median()

print(f"Calculos de Mediana:")
print(f"  Pagamento Mensal: {mediana_pagamento}")
print(f"  Tempo Como Cliente: {mediana_tempo}")
print(f"  Total pago: {mediana_total}")

Calculos de Mediana:
  Pagamento Mensal: 71.1
  Tempo Como Cliente: 29.0
  Total pago: 1402.9

Identificação de outliers:

In [7]:
colunas_numericas = [
    "Pagamento_Mensal",
    "Tempo_como_Cliente",
    "Total_Pago"
                     ]

for coluna in colunas_numericas:
    fig = px.box(
        df,
        x=coluna,
        points='outliers',

        title=f'Boxplot interativo - {coluna}',
        labels={coluna: coluna},

    )

    fig.update_xaxes(
        tickprefix="R$ ",
        tickformat=",.2f"
    )

    fig.update_layout(
        separators=",."
    )

    fig.show()

In [8]:
colunas_valores = [
    "Pagamento_Mensal",
    "Tempo_como_Cliente",
    "Total_Pago"
]

for coluna in colunas_valores:
    Q1 = df[coluna].quantile(0.25)
    Q3 = df[coluna].quantile(0.75)
    IQR = Q3 - Q1

    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    outliers = df[
        (df[coluna] < limite_inferior) |
        (df[coluna] > limite_superior)
    ] 


    print(f"\nColuna: {coluna}")
    print(f"Q1: {Q1}")
    print(f"Q3: {Q3}")
    print(f"IQR: {IQR}")
    print(f"Limite superior: {limite_superior}")
    print(f"Limite inferior: {limite_inferior}")
    print(f"Outliers: {len(outliers)}")

Coluna: Pagamento_Mensal
Q1: 39.6375
Q3: 90.25
IQR: 50.6125
Limite superior: 166.16875
Limite inferior: -36.281249999999986
Outliers: 0

Coluna: Tempo_como_Cliente
Q1: 8.0
Q3: 56.0
IQR: 48.0
Limite superior: 128.0
Limite inferior: -64.0
Outliers: 0

Coluna: Total_Pago
Q1: 402.3375
Q3: 3867.1625
IQR: 3464.825
Limite superior: 9064.4
Limite inferior: -4794.9
Outliers: 0

In [9]:
colunas_boolean = [
    "Servico_Seguranca",
    "Suporte_Tecnico",
    "StreamingTV",
    "Casado",
    "Dependentes",
    "Churn"
]

for coluna in colunas_boolean:
    contagem_valores = (
        df[coluna]
        .value_counts()
        .reindex([0,1],fill_value=0)
        .rename_axis('Valor')
        .reset_index(name='Quantidade')
    )

    contagem_valores['Categoria'] = contagem_valores['Valor'].map({
        0:'Não',
        1:'Sim'
    })

    fig = px.bar(
        contagem_valores,
        x='Categoria',
        y='Quantidade',
        text='Quantidade',
        color='Categoria',
        title=f"Distribuição da variável {coluna}",
        labels={
            'Categoria': coluna,
            'Quantidade': 'Quantidade'
        },
        category_orders={
            'Categoria':['Não','Sim']
        }
    )    

    fig.update_traces(textposition='outside')
    fig.update_layout(showlegend=False, autosize=False, width=1200, height=800)


    pd.set_option('display.width', 1000)
    print(f"\n{coluna}")
    print(contagem_valores.to_string(index=False))
    fig.show()

Servico_Seguranca
 Valor  Quantidade Categoria
     0        1781       Não
     1         707       Sim

Suporte_Tecnico
 Valor  Quantidade Categoria
     0        1777       Não
     1         711       Sim

StreamingTV
 Valor  Quantidade Categoria
     0        1528       Não
     1         960       Sim

Casado
 Valor  Quantidade Categoria
     0        1262       Não
     1        1226       Sim

Dependentes
 Valor  Quantidade Categoria
     0        1705       Não
     1         783       Sim

Churn
 Valor  Quantidade Categoria
     0        1841       Não
     1         647       Sim

*Os gráficos referentes às variáveis booleanas no mostram que só são balanceados na coluna 'Casado', porém todos os registros apresentam um número considerável em ambas as categorias de resposta.*

# 3) Identifique e trate as colunas que contém outliers.
Caso opte por mante-los ou altera-los justifique sua escolha.

- *Como analizamos na etapa anterior, não há presença de outliers em nenhuma das variáveis numéricas.*

# 4) Realize a etapa da análise bivariada:
A) Questione pelo menos 5 informações e traga as respostas utilizando visuais gráficos e insights.


B) Quais variáveis você acredita serem as mais importantes para esse projetos relacionadas a variável Churn?


### Análise bivariada:
#### - Questionamento 1: Qual o produto mais vendido?

In [10]:
colunas_produtos = [
    "Servico_Internet",
    "Servico_Seguranca",
    "Suporte_Tecnico",
    "StreamingTV"
    ]

df_contratados = df[colunas_produtos].map(
    lambda valor: 0 if str(valor).strip() == "0" else 1
)

total_clientes = len(df)
total_por_produto = df_contratados.sum().reset_index()
total_por_produto.columns = ["Produto","Quantidade"]
total_por_produto["Porcentagem"] = round((total_por_produto["Quantidade"]/total_clientes) * 100, 2)

print(total_por_produto)

             Produto  Quantidade  Porcentagem
0   Servico_Internet        1961        78.82
1  Servico_Seguranca         707        28.42
2    Suporte_Tecnico         711        28.58
3        StreamingTV         960        38.59

In [11]:
total_por_produto_ordenado = total_por_produto.sort_values(by="Quantidade", ascending=True)

fig = px.bar(
    total_por_produto_ordenado,
    x="Produto",
    y="Porcentagem",
    text="Porcentagem",
    color="Produto",
    title="Quantidade contratada por produto",
    labels= {
        "Produto":"Produto",
        "Porcentagem":"Porcentagem"
    }
)

fig.update_traces(
    textposition='outside',
    texttemplate='%{text:,d}'
    )

fig.update_layout(
    showlegend=False, 
    autosize=True,
    height= 800,
    bargap=0.6,
    margin=dict(t=80, b=40, l=40, r=40), 
    title_x=0.5
    )


pd.set_option('display.width', 1200)

fig.show()

Podemos visualizar algo que já é de se esperar do mercado de serviços telefônicos, a grande maioria dos clientes possui o serviço de internet contratado.

#### - Questionamento 2: Quantos clientes possuem mais de um serviço contratado?

In [12]:
df["total_produtos_por_cliente"] = df_contratados.sum(axis=1)

cliente_multi_produto = (df["total_produtos_por_cliente"] > 1).sum()
total_clientes = len(df)
porcentagem = round((cliente_multi_produto/total_clientes) * 100, 2)

print(f"{cliente_multi_produto} clientes ({porcentagem} %) contrataram mais de um serviço.")

1424 clientes (57.23 %) contrataram mais de um serviço.

In [13]:
clientes_multi = df_contratados[df["total_produtos_por_cliente"] > 1]
clientes_internet = (clientes_multi["Servico_Internet"] == 1)
print(clientes_multi["Servico_Internet"].unique())
print(f"{clientes_internet.sum()} possuem o serviço de internet entre aqueles que possuem mais de um serviço.")

[1]
1424 possuem o serviço de internet entre aqueles que possuem mais de um serviço.

- Entre os clientes que contratam mais de um serviço, 100% deles contrataram o serviço de internet. Isso é importante para futuros insights.

In [14]:
correlacao = df_contratados.corr()

fig = px.imshow(
    correlacao,
    text_auto=".2f",
    color_continuous_scale="Purples",
    title="<b>Matriz de correlação entre os seviços contratados</b>",
    labels=dict(color="Correlação"),
    x=correlacao.columns,
    y=correlacao.columns
)


fig.update_layout(
    width=700,
    height=600,
    title_x=0.5
)

fig.show()

#### - Insights do gráfico:
- A maior correlação do gráfico é entre o serviço de internet e streaming de TV, o que pode sugerir um pacote de entretenimento vendido para os cliente.
- A menor correlação é entre streaming e serviço de segurança, o que parece coerente, com um produto que é complementar de serviços de internet em geral.

#### - Questionamento 3: Qual o perfil do cliente que possui dependentes e do que não possui?

In [34]:
def tracar_perfil(coluna):
    """
    Traça o perfil de cliente em relação ao consumo atrelado à família.
    """
    if coluna["Casado"] and coluna["Dependentes"] == 1:
        return "Casado com dependentes"
    elif coluna["Casado"] == 1 and coluna["Dependentes"] == 0:
        return "Casado sem dependentes"
    elif coluna["Casado"] == 0 and coluna["Dependentes"] == 1:
        return "Solteiro com dependentes"
    else:
        return "Solteiro sem dependentes"

df["Perfil_Familia"] = df.apply(tracar_perfil, axis=1).sort_values(ascending=True)

print(df["Perfil_Familia"].value_counts())

Perfil_Familia
Solteiro sem dependentes    1142
Casado com dependentes       663
Casado sem dependentes       563
Solteiro com dependentes     120
Name: count, dtype: int64

In [38]:
df[colunas_produtos] = df_contratados

perfil_produtos = (
    df.groupby("Perfil_Familia")[colunas_produtos].mean() * 100
).round(2)

print(perfil_produtos)

                          Servico_Internet  Servico_Seguranca  Suporte_Tecnico  StreamingTV
Perfil_Familia
Casado com dependentes               72.25              36.95            34.09        41.78
Casado sem dependentes               86.68              34.28            32.50        46.18
Solteiro com dependentes             62.50              26.67            21.67        24.17
Solteiro sem dependentes             80.47              20.75            24.17        34.50

In [39]:
df_grafico = perfil_produtos.reset_index().melt(
    id_vars="Perfil_Familia", var_name="Produto", value_name="Taxa_Adesao_Pct"
).sort_values(by="Taxa_Adesao_Pct", ascending=True)

fig = px.bar(
    df_grafico,
    x="Perfil_Familia",
    y="Taxa_Adesao_Pct",
    color="Produto",
    barmode="group",
    text="Taxa_Adesao_Pct",
    title="<b>Taxa de Adesão aos Produtos por Perfil Familiar (%)</b>",
    labels={
        "Perfil_Familia": "Perfil Familia",
        "Taxa_Adesao_Pct": "Adesão (%)",
    },
    color_discrete_sequence=px.colors.qualitative.Set2,
)

fig.update_traces(texttemplate="%{text}%", textposition="outside")
fig.update_layout(
    height=500, width=850, yaxis_range=[0, 100], title_x=0.5, legend_title="Produto"
)

fig.show()

Percebemos que clientes <b>casados</b> costumam a contratar mais o serviço de entretenimento em questão. Com os clientes casados e sem dependentes com um número ligeiramente maior, porém, em relação aos serviços de manutenção estes clientes são os que mais possuem contratos, o que pode indicar que clientes com mais usuários costumam a optar por um pacote mais completo de produtos.

### Questionamento 4: Qual o modelo de contrato mais sustentável à longo prazo?

In [45]:
resumo_medidas = (
    df.groupby("Churn")[colunas_numericas].mean().round(2).reset_index()
)

print(f"========= Média das variáveis numéricas por Churn =========")
print(resumo_medidas)

========= Média das variáveis numéricas por Churn =========
   Churn  Pagamento_Mensal  Tempo_como_Cliente  Total_Pago
0      0             61.86               37.41     2546.92
1      1             75.89               17.95     1559.27

In [54]:
for coluna in colunas_numericas:
    fig = px.box(
        df,
        x=coluna,
        y="Churn",
        color="Churn",
        title=f"<b>Distribuição de {coluna} por Churn</b>",
        labels={"Churn": "Churn", coluna: coluna},
        color_discrete_sequence=["#636EFA", "#EF553B"],
        orientation="h"
    )
    fig.update_layout(width=1000, height=700, title_x=0.5, showlegend=False)
    fig.show()

Os clientes costumam a cancelar o serviço nos primeiros meses, o que acusa um problema de retenção de clientes.

In [55]:
churn_tipo_contrato = (
    df.groupby("Tipo_Contrato")["Churn"]
    .agg(Total_Clientes="count", Churn_Total="sum")
    .reset_index()
)

churn_tipo_contrato["Taxa_Churn_Pct"] = (
    churn_tipo_contrato["Churn_Total"] / churn_tipo_contrato["Total_Clientes"] * 100
).round(2)

print("========= Taxa de Churn por Tipo de Contrato =========")
print(churn_tipo_contrato)

========= Taxa de Churn por Tipo de Contrato =========
    Tipo_Contrato  Total_Clientes  Churn_Total  Taxa_Churn_Pct
0  Month-to-month            1369          580           42.37
1        One year             517           58           11.22
2        Two year             602            9            1.50

In [57]:
fig = px.bar(
    churn_tipo_contrato.sort_values(by="Taxa_Churn_Pct",ascending=True),
    x="Tipo_Contrato",
    y="Taxa_Churn_Pct",
    text="Taxa_Churn_Pct",
    color="Tipo_Contrato",
    title="<b>Taxa de Churn (%) por Tipo de Contrato</b>",
    labels={
        "Tipo_Contrato": "Tipo de Contrato",
        "Taxa_Churn_Pct": "Taxa de Churn (%)",
    },
    color_discrete_sequence=px.colors.qualitative.Safe,
)

fig.update_traces(texttemplate="%{text}%", textposition="outside")
fig.update_layout(height=450, width=700, title_x=0.5, yaxis_range=[0, 100])
fig.show()

### Questionamento 5: Quais variáveis possuem a maior correlação com churn?

In [67]:

vertentes = ["Tempo_como_Cliente", "Total_Pago"]

correlacao = (
    df[vertentes + ["Churn"]]
    .corr()["Churn"]
    .drop("Churn")
    .abs()
    .reset_index()
)
correlacao.columns = ["Vertente", "Forca_Relacao"]
correlacao["Vertente"] = correlacao["Vertente"].map(
    {
        "Tempo_como_Cliente": "Tempo como Cliente",
        "Total_Pago": "Valor Total Pago",
    }
)
correlacao = correlacao.sort_values(by="Forca_Relacao", ascending=True)

fig = px.bar(
    correlacao,
    x="Forca_Relacao",
    y="Vertente",
    orientation="h",
    text=correlacao["Forca_Relacao"].apply(lambda x: f"{x:.2f}"),
    color="Forca_Relacao",
    color_continuous_scale="Purples",
    title="<b>Comparativo da Relação das Vertentes com o Churn</b>",
    labels={
        "Forca_Relacao": "Grau de Relação / Associação",
        "Vertente": "Vertente Analisada",
    },
)

fig.update_traces(textposition="outside")
fig.update_layout(
    height=400,
    width=750,
    title_x=0.5,
    xaxis_range=[0, 1.0],
    coloraxis_showscale=False,
)

fig.show()

#### 4) B. 

Após todas as análises, concluímos que a variável que mais influencia no churn é o tempo como cliente, sendo que grande parte dos clientes que cancelaram seus planos estavam em seu primeiro ano de plano. Também conferimos que clientes que pagam mais mensalmente, tendem a dar churn eventualmente, o que indica que o modelo de contrato de destaque deve ser o anual.