# **MÓDULO 15 - Exercício**
# Análise  - A segunda etapa da Pré Modelagem

# 1) O primeiro exercício é o de salvar a base que criaram na atividade do módulo anterior em csv e abrir ela neste arquivo.
Igual fizemos no início do módulo atual no início da primeira aula.

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import plotly.express as px

In [16]:
#Seu código de importação aqui
df = pd.read_csv("CHURN_TRATADO.csv", delimiter=",")
df.head(10)

,Unnamed: 0,customerID,Genero,Idoso,Casado,Dependentes,Tempo_como_Cliente,Servico_Telefonico,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,Forma_Pagamento,Pagamento_Mensal,Total_Pago,Churn
0,0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.850000,29.85,No
1,1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.950000,1889.50,No
2,2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.850000,108.15,Yes
3,3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),40.905556,1840.75,No
4,16,8191-XWSZG,Female,0,No,No,52,Yes,No,No internet service,No internet service,No internet service,One year,Mailed check,19.672115,1022.95,No
5,17,9959-WOFKT,Male,0,No,Yes,71,Yes,Fiber optic,Yes,No,Yes,Two year,Bank transfer (automatic),103.975352,7382.25,No
6,18,4190-MFLUW,Female,0,Yes,Yes,10,Yes,DSL,No,Yes,No,Month-to-month,Credit card (automatic),52.835000,528.35,Yes
7,19,4183-MYFRB,Female,0,No,No,21,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,88.709524,1862.90,No
8,20,8779-QRDMV,Male,1,No,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,39.650000,39.65,Yes
9,21,1680-VDCWW,Male,0,Yes,No,12,Yes,No,No internet service,No internet service,No internet service,One year,Bank transfer (automatic),16.854167,202.25,No

In [17]:
df = df.replace({'Yes':1,'No':0})
df = df.replace({'No internet service':0})
df = df.drop(columns=['Servico_Telefonico'])

colunas = ['Servico_Seguranca','Suporte_Tecnico','StreamingTV','Casado','Dependentes','Churn']

df[colunas] = df[colunas].astype(int)

C:\Users\tec01\AppData\Local\Temp\ipykernel_19108\2760767357.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'Yes':1,'No':0})
C:\Users\tec01\AppData\Local\Temp\ipykernel_19108\2760767357.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'No internet service':0})

In [18]:
print(df.dtypes)

Unnamed: 0              int64
customerID             object
Genero                 object
Idoso                   int64
Casado                  int64
Dependentes             int64
Tempo_como_Cliente      int64
Servico_Internet       object
Servico_Seguranca       int64
Suporte_Tecnico         int64
StreamingTV             int64
Tipo_Contrato          object
Forma_Pagamento        object
Pagamento_Mensal      float64
Total_Pago            float64
Churn                   int64
dtype: object

# 2) Comece pela análise univariada:

A) Utilize a função describe no seu dataframe, veja os insights que consegue retirar.

B) Já é possível identificar variáveis com possíveis outliers? Se sim, quais?

C) Plot gráficos que considerar importante para completar sua análise univariada. (Lembrando que sua variável preditora é o churn). Não se esqueça de trazer insights de cada gráfico plotado. Utilize pelo menos 4 variáveis distintas.

D) Verifique se os dados das variáveis Booleanas são balanceados ou não.

In [19]:
#Seu código aqui
df.describe()

,Unnamed: 0,Idoso,Casado,Dependentes,Tempo_como_Cliente,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Pagamento_Mensal,Total_Pago,Churn
count,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000,2488.000000
mean,1255.480707,0.161576,0.492765,0.314711,32.352090,0.284164,0.285772,0.385852,65.511708,2290.087178,0.260048
std,718.401587,0.368135,0.500048,0.464494,24.636885,0.451106,0.451872,0.486894,29.920953,2264.585643,0.438749
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.725000,18.800000,0.000000
25%,633.750000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,0.000000,39.637500,402.337500,0.000000
50%,1255.500000,0.000000,0.000000,0.000000,29.000000,0.000000,0.000000,0.000000,71.100000,1402.900000,0.000000
75%,1877.250000,0.000000,1.000000,1.000000,56.000000,1.000000,1.000000,1.000000,90.250000,3867.162500,1.000000
max,2499.000000,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,1.000000,121.400000,8564.750000,1.000000

# 3) Identifique e trate as colunas que contém outliers.
Caso opte por mante-los ou altera-los justifique sua escolha.

In [ ]:
#Seu código aqui

# 4) Realize a etapa da análise bivariada:
A) Questione pelo menos 5 informações e traga as respostas utilizando visuais gráficos e insights.


B) Quais variáveis você acredita serem as mais importantes para esse projetos relacionadas a variável Churn?

In [ ]:
#Seu código aqui